### this file contains the request done through server side rest api

GET http://localhost:5000/auth/user
Content-Type: application/json

{
    "name":"snehal",
    "company":"Pepcoding",
    "address":"Noida",
    "email":"priyanka@gmail.com",
    "password":"12345"
    
}

### insert new user
POST http://localhost:5000/auth/
Content-Type: application/json

{
    "name":"snehal",
    "company":"Pepcoding",
    "address":"Noida",
    "email":"diggidon29@gmail.com",
    "password":"12345"
    
}
### user singin EndPoint
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    
    "email":"diggidon29@gmail.com",
     "password":"Pepcoding123"
   
    
}

### authorization endpoint
GET  http://localhost:5000/auth/user
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoicHJpeWFua2FAZ21haWwuY29tIiwiaWF0IjoxNjU5ODU5ODg5LCJleHAiOjE2NTk4NTk5NDl9.CiVom27gaqXorERsh3JqpIUIMy4IJOMU7S7PW1uU5Rk


### get the refresh tokens from the mongodb
GET http://localhost:5000/token/fresh-access-jwt
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoicHJpeWFua2FAZ21haWwuY29tIiwiaWF0IjoxNjU5ODU0MDkzLCJleHAiOjE2NjA0NTg4OTN9.N3TS6EVjz5hrJ52zifxYrRFDEXPkWTOH3C_3z1DNB08


### resest-password endpoint
POST http://localhost:5000/auth/reset-password
Content-Type: application/json

{
    
    "email":"diggidon29@gmail.com"   
}

### update-password endpoint
PATCH http://localhost:5000/auth/update-password
Content-Type: application/json

{
    "email":"diggidon29@gmail.com" ,
    "pin":"516547",
    "newPassword":"Pepcoding123"
}

